### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by rilyuuj** [hackyes/BaiduExporter#1]
感谢fork，原作者这个project被删了，请问是什么原因？
这个fork的版本是作者什么时候更新的，能告知下么？

**Comment by hackyes** [comment]
原作者我也不知道怎么删了，这只是备份过来的。

rilyuuj <notifications@github.com> 于2020年5月15日周五 下午12:05写道：

**Comment by rilyuuj** [comment]
好的，谢谢。
不过事件之后发现很多作者都吧项目删掉了，之前一个js的相关也没repo了，只留了一个空的使用指南网站。。。
